-- 夫婦家計管理アプリ スキーマ（PostgreSQL）
-- id は明示指定もできるよう GENERATED BY DEFAULT にしている（データ移行で元のidを保つため）。

CREATE TABLE IF NOT EXISTS people (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  display_order INTEGER NOT NULL DEFAULT 0
);

-- 「プランA／プランB」のようにシナリオ（想定値の組）を複数持つ。
-- 想定値はプランごと、実績は全プラン共通。
CREATE TABLE IF NOT EXISTS plans (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  display_order INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL
);

-- アクティブなプランなど、アプリ全体の状態を持つ
CREATE TABLE IF NOT EXISTS app_state (
  key TEXT PRIMARY KEY,
  value TEXT
);

-- プラン共通の前提（金額でないものだけ。金額は人ごとに持つ）
CREATE TABLE IF NOT EXISTS plan_settings (
  plan_id INTEGER PRIMARY KEY REFERENCES plans(id),
  simulation_start_month TEXT NOT NULL,
  starting_balance_month TEXT NOT NULL,
  expected_annual_return_pct DOUBLE PRECISION NOT NULL DEFAULT 5.0,
  compounding TEXT NOT NULL DEFAULT 'monthly' CHECK (compounding IN ('monthly','annually'))
);

-- 想定値はすべて人ごと。世帯合計は二人分を足して算出する。
CREATE TABLE IF NOT EXISTS plan_person_assumptions (
  plan_id INTEGER NOT NULL REFERENCES plans(id),
  person_id INTEGER NOT NULL REFERENCES people(id),
  monthly_income_assumption INTEGER NOT NULL DEFAULT 0,
  monthly_credit_card_assumption INTEGER NOT NULL DEFAULT 0,
  rent_assumption INTEGER NOT NULL DEFAULT 0,
  investment_contribution_assumption INTEGER NOT NULL DEFAULT 0,
  other_expense_assumption INTEGER NOT NULL DEFAULT 0,
  other_cash_expense_assumption INTEGER NOT NULL DEFAULT 0,
  starting_cash_balance INTEGER NOT NULL DEFAULT 0,
  starting_investment_balance INTEGER NOT NULL DEFAULT 0,
  cash_sweep_threshold INTEGER,   -- 現金がこの額を超えたら超過分を投資へ。NULLなら振替しない
  PRIMARY KEY (plan_id, person_id)
);

-- 毎月の想定額を、期間を区切って変える場合の上書き値。
-- 例：「2026-04〜2027-03は月収35万円、それ以降は38万円」。
-- 該当する期間の行が無い月は plan_person_assumptions の基本値を使う。
-- 同じ月に複数該当する場合は start_month が一番遅い（＝一番新しい）行を優先する。
CREATE TABLE IF NOT EXISTS plan_assumption_periods (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  plan_id INTEGER NOT NULL REFERENCES plans(id),
  person_id INTEGER NOT NULL REFERENCES people(id),
  field TEXT NOT NULL CHECK (field IN (
    'monthly_income_assumption', 'monthly_credit_card_assumption', 'rent_assumption',
    'investment_contribution_assumption', 'other_expense_assumption',
    'other_cash_expense_assumption'
  )),
  start_month TEXT NOT NULL,  -- 'YYYY-MM'。この月から適用
  end_month TEXT,             -- 'YYYY-MM'。NULLなら以降ずっと適用
  amount INTEGER NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_pap_lookup
  ON plan_assumption_periods(plan_id, person_id, field);

-- 住宅・不動産。賃貸の家賃と違い、ローン開始月から毎月の返済額ぶん現金が減る代わりに、
-- 同額が（投資拠出とまったく同じ仕組みで）年率の値動きを乗せながら資産として積み上がる。
-- ローン完済後は返済が止まり、評価額はそのまま年率で変動し続ける。金利・元利内訳・
-- 残債は扱わない（返済額がそのまま持分の積み立てになるとみなす単純化モデル）。
-- シナリオで変わりうるためプランごとに持つ。単独所有のみ（共有持分は非対応）。
CREATE TABLE IF NOT EXISTS plan_real_estate (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  plan_id INTEGER NOT NULL REFERENCES plans(id),
  person_id INTEGER NOT NULL REFERENCES people(id),
  label TEXT NOT NULL,
  purchase_month TEXT NOT NULL,          -- 'YYYY-MM'。ローン返済の開始月
  monthly_payment INTEGER NOT NULL,      -- 毎月の返済額（家賃の代わりに支払う額）
  loan_term_months INTEGER NOT NULL,     -- 返済期間（月数）。例：35年なら420
  annual_appreciation_pct DOUBLE PRECISION NOT NULL DEFAULT 0,  -- 負の値で値下がり
  notes TEXT
);
CREATE INDEX IF NOT EXISTS idx_pre_lookup ON plan_real_estate(plan_id, person_id);

-- 実績も人ごと。全プラン共通（事実なのでシナリオでは変わらない）。
CREATE TABLE IF NOT EXISTS monthly_person_actuals (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  person_id INTEGER NOT NULL REFERENCES people(id),
  month TEXT NOT NULL,
  income INTEGER,
  rent INTEGER,
  investment_contribution INTEGER,
  other_expense INTEGER,
  bank_cash_balance_eom INTEGER,
  investment_balance_eom INTEGER,
  notes TEXT,
  UNIQUE(person_id, month)
);

CREATE TABLE IF NOT EXISTS credit_cards (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  owner_person_id INTEGER REFERENCES people(id)
);

CREATE TABLE IF NOT EXISTS csv_import_batches (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  card_id INTEGER NOT NULL REFERENCES credit_cards(id),
  imported_at TEXT NOT NULL,
  filename TEXT,
  row_count INTEGER,
  skipped_duplicate_count INTEGER,
  total_amount INTEGER
);

CREATE TABLE IF NOT EXISTS credit_card_transactions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  card_id INTEGER NOT NULL REFERENCES credit_cards(id),
  txn_date TEXT NOT NULL,
  month TEXT NOT NULL,
  description TEXT,
  amount INTEGER NOT NULL,
  category TEXT,
  import_batch_id INTEGER REFERENCES csv_import_batches(id),
  UNIQUE(card_id, txn_date, description, amount)
);
CREATE INDEX IF NOT EXISTS idx_cct_month ON credit_card_transactions(month);

-- クレジットカード支出の実績は人ごとに管理する（夫のカード/妻のカードで別々に入力）。
CREATE TABLE IF NOT EXISTS monthly_credit_card_actuals (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  person_id INTEGER NOT NULL REFERENCES people(id),
  month TEXT NOT NULL,
  amount INTEGER NOT NULL,
  source TEXT NOT NULL DEFAULT 'manual' CHECK (source IN ('manual', 'csv')),
  UNIQUE(person_id, month)
);

-- ボーナスなどの臨時収入・イベント出費。単発（once）または毎年繰り返し（yearly）。
-- シナリオ差が最も出る部分なのでプランごとに持つ。
CREATE TABLE IF NOT EXISTS planned_items (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  plan_id INTEGER REFERENCES plans(id),
  item_type TEXT NOT NULL CHECK (item_type IN ('income', 'expense')),
  label TEXT NOT NULL,
  amount INTEGER NOT NULL,
  person_id INTEGER REFERENCES people(id),
  recurrence TEXT NOT NULL DEFAULT 'once' CHECK (recurrence IN ('once', 'yearly')),
  month TEXT,              -- 'YYYY-MM'。recurrence='once' のとき必須
  month_of_year INTEGER,   -- 1-12。recurrence='yearly' のとき必須
  start_year INTEGER,      -- yearly専用。NULLなら下限なし
  end_year INTEGER,        -- yearly専用。NULLなら上限なし
  notes TEXT
);
